{-# OPTIONS --cubical --guardedness #-}

module Exercises.Arithmetic.Notes-on-Natural-Number-Arithmetic where

open import Cubical.Foundations.Prelude using (_≡_; refl; cong; sym; _∙_)
open import Cubical.Data.Nat.Base using (ℕ; zero; suc; _+_; _·_)


{-
Theorem 1: Right identity of zero for addition

Statement
---------
For every natural number n,
  n + zero ≡ n.

Relevant definitions
--------------------
The natural numbers are generated by zero and suc.
Addition recurses on its first argument:
  zero  + m = m
  suc n + m = suc (n + m)

Previous results and tools
--------------------------
No previous arithmetic theorem is needed.
refl proves an equality whose two sides reduce to the same expression.
If p : x ≡ y, then cong suc p : suc x ≡ suc y.

Path calculation
----------------
zero case:
  zero + zero
    ≡ zero                         [definition] by the equation zero + m = m

suc case:
  suc n + zero
    ≡ suc (n + zero)               [definition] by the equation suc n + m = suc (n + m)
    ≡ suc n                        [induction hypothesis] by cong suc applied to +-zeroʳ n

Here +-zeroʳ n is not a previously completed theorem: it is the induction
hypothesis, namely the same statement at the structurally smaller number n.
-}

+-zeroʳ : (n : ℕ) → n + zero ≡ n
+-zeroʳ zero = refl
+-zeroʳ (suc n) = cong suc (+-zeroʳ n)


{-
Theorem 2: Left identity of zero for addition

Statement
---------
For every natural number n,
  zero + n ≡ n.

Relevant definitions
--------------------
Addition recurses on its first argument:
  zero  + m = m
  suc n + m = suc (n + m)

Previous results and tools
--------------------------
No previous theorem is needed. Since the first argument is already zero,
the expression reduces directly by definition and refl closes the goal.

Path calculation
----------------
zero case:
  zero + zero
    ≡ zero                         [definition] by the equation zero + m = m

suc case:
  zero + suc n
    ≡ suc n                        [definition] by the equation zero + m = m

Both cases are covered by the single proof `+-zeroˡ n = refl`; no induction
or case split is required in the code.
-}

+-zeroˡ : (n : ℕ) → zero + n ≡ n
+-zeroˡ n = refl

{-
Theorem 3: Associativity of addition

Statement
---------
For all natural numbers a, b, and c,
  (a + b) + c ≡ a + (b + c).

Relevant definitions
--------------------
Addition recurses on its first argument:
  zero  + m = m
  suc n + m = suc (n + m)

Previous results and tools
--------------------------
No previous arithmetic theorem is required.
The suc case uses the induction hypothesis +-assoc a b c under cong suc.

Path calculation
----------------
zero case:
  (zero + b) + c
    ≡ b + c                        [definition] by reducing zero + b
    ≡ zero + (b + c)               [definition] by reading zero + (b + c) = b + c backwards

suc case:
  (suc a + b) + c
    ≡ suc ((a + b) + c)            [definition] by unfolding both additions with first argument suc
    ≡ suc (a + (b + c))            [induction hypothesis] by cong suc applied to +-assoc a b c
    ≡ suc a + (b + c)              [definition] by folding suc a + (b + c)

In the middle step, +-assoc a b c is the induction hypothesis because the
current clause proves +-assoc (suc a) b c.

Only a is used as the induction variable; no induction on b or c is needed.
-}

+-assoc : (a b c : ℕ) → (a + b) + c ≡ a + (b + c)
+-assoc zero b c = refl
+-assoc (suc a) b c = cong suc (+-assoc a b c)

{-
Supporting lemma for Theorem 4: Successor in the right argument

Statement
---------
For all natural numbers n and m,
  n + suc m ≡ suc (n + m).

Relevant definitions
--------------------
Addition unfolds automatically only when its first argument is zero or suc:
  zero  + m = m
  suc n + m = suc (n + m)

The desired equality concerns a successor in the second argument, so it is
not a definitional equality for arbitrary n. We prove it by induction on n.

Previous results and tools
--------------------------
No previous arithmetic theorem is required.
The suc case applies cong suc to the induction hypothesis +-sucʳ n m.

Path calculation
----------------
zero case:
  zero + suc m
    ≡ suc m                        [definition] by reducing zero + suc m
    ≡ suc (zero + m)               [definition] by folding zero + m inside suc

suc case:
  suc n + suc m
    ≡ suc (n + suc m)              [definition] by unfolding addition at suc n
    ≡ suc (suc (n + m))            [induction hypothesis] by cong suc applied to +-sucʳ n m
    ≡ suc (suc n + m)              [definition] by folding suc n + m inside the outer suc

Here +-sucʳ n m is the induction hypothesis for the smaller first argument n.
-}
+-sucʳ : (n m : ℕ) → n + suc m ≡ suc (n + m)
+-sucʳ zero m = refl
+-sucʳ (suc n) m = cong suc (+-sucʳ n m)

{-
Theorem 4: Commutativity of addition

Statement
---------
For all natural numbers a and b,
  a + b ≡ b + a.

Relevant definitions
--------------------
Addition recurses on its first argument:
  zero  + m = m
  suc n + m = suc (n + m)

Previous results and tools
--------------------------
  +-zeroʳ b : b + zero ≡ b
  +-sucʳ b a : b + suc a ≡ suc (b + a)
  sym p reverses a path.
  p ∙ q composes two paths whose endpoints match.

Path calculation
----------------
zero case:
  zero + b
    ≡ b                            [definition] by reducing zero + b
    ≡ b + zero                     [previous theorem] by sym (+-zeroʳ b), using Theorem 1

suc case:
  suc a + b
    ≡ suc (a + b)                  [definition] by unfolding addition at suc a
    ≡ suc (b + a)                  [induction hypothesis] by cong suc applied to +-comm a b
    ≡ b + suc a                    [previous lemma] by sym (+-sucʳ b a)

The occurrence +-comm a b is the induction hypothesis for the smaller first
argument a. In contrast, +-sucʳ b a is the supporting lemma completed above.
-}

+-comm : (a b : ℕ) → a + b ≡ b + a
+-comm zero b = sym (+-zeroʳ b)
+-comm (suc a) b = ( cong suc (+-comm a b) ) ∙ ( sym (+-sucʳ b a) )



{-
Theorem 5: Right annihilation by zero for multiplication

Statement
---------
For every natural number n,
  n · zero ≡ zero.

Relevant definitions
--------------------
Multiplication recurses on its first argument:
  zero  · m = zero
  suc n · m = m + (n · m)

Addition satisfies the defining equation:
  zero + k = k

Previous results and tools
--------------------------
No previous theorem is needed. In the suc case, unfolding multiplication and
addition reduces the new goal exactly to the induction hypothesis ·-zeroʳ n.

Path calculation
----------------
zero case:
  zero · zero
    ≡ zero                         [definition] by the equation zero · m = zero

suc case:
  suc n · zero
    ≡ zero + (n · zero)            [definition] by unfolding multiplication at suc n
    ≡ n · zero                     [definition] by reducing zero + (n · zero)
    ≡ zero                         [induction hypothesis] by ·-zeroʳ n

The first two steps are definitional, so the Agda clause can be written simply
as `·-zeroʳ (suc n) = ·-zeroʳ n`.
-}



·-zeroʳ : (n : ℕ) → n · zero ≡ zero
·-zeroʳ zero = refl
·-zeroʳ (suc n) = ·-zeroʳ n



{-
Theorem 6: Right distributivity of multiplication over addition

Statement
---------
For all natural numbers a, b, and c,
  (a + b) · c ≡ (a · c) + (b · c).

The right factor c is fixed, hence the name "right distributivity" here.

Relevant definitions
--------------------
Addition and multiplication both recurse on their first arguments:
  zero  + b = b
  suc a + b = suc (a + b)
  zero  · c = zero
  suc a · c = c + (a · c)

Previous results and tools
--------------------------
  +-assoc c (a · c) (b · c) :
    (c + a · c) + b · c ≡ c + (a · c + b · c)

The suc case also uses the induction hypothesis ·-distribʳ-+ a b c under
the outer function `c +_`.

Path calculation
----------------
zero case:
  (zero + b) · c
    ≡ b · c                        [definition] by reducing zero + b
    ≡ zero + b · c                 [definition] by folding zero + b · c
    ≡ zero · c + b · c             [definition] by folding zero · c

suc case:
  (suc a + b) · c
    ≡ c + ((a + b) · c)            [definition] by unfolding _+_ at suc a and then _·_
    ≡ c + (a · c + b · c)          [induction hypothesis] by cong (c +_) applied to ·-distribʳ-+ a b c
    ≡ (c + a · c) + b · c          [previous theorem] by sym (+-assoc c (a · c) (b · c)), using Theorem 3
    ≡ suc a · c + b · c            [definition] by folding suc a · c

The recursive occurrence ·-distribʳ-+ a b c is the induction hypothesis for
the current clause ·-distribʳ-+ (suc a) b c. The use of +-assoc is different:
it calls the previously completed associativity theorem for addition.
-}

·-distribʳ-+ : (a b c : ℕ) → (a + b) · c ≡ (a · c) + (b · c)
·-distribʳ-+ zero b c = refl
·-distribʳ-+ (suc a) b c = (cong (λ x → c + x) (·-distribʳ-+ a b c) ) ∙ (sym (+-assoc c (a · c) (b · c)) )

{-
Theorem 7: Associativity of multiplication

Statement
---------
For all natural numbers a, b, and c,
  (a · b) · c ≡ a · (b · c).

Relevant definitions
--------------------
Multiplication recurses on its first argument:
  zero  · b = zero
  suc a · b = b + (a · b)

Previous results and tools
--------------------------
  ·-distribʳ-+ b (a · b) c :
    (b + a · b) · c ≡ b · c + (a · b) · c

The suc case also uses the induction hypothesis ·-assoc a b c under the
outer function `b · c +_`.

Path calculation
----------------
zero case:
  (zero · b) · c
    ≡ zero                         [definition] by reducing zero · b and then zero · c
    ≡ zero · (b · c)               [definition] by folding zero · (b · c)

suc case:
  (suc a · b) · c
    ≡ (b + a · b) · c              [definition] by unfolding suc a · b
    ≡ b · c + (a · b) · c          [previous theorem] by ·-distribʳ-+ b (a · b) c, using Theorem 6
    ≡ b · c + a · (b · c)          [induction hypothesis] by cong (b · c +_) applied to ·-assoc a b c
    ≡ suc a · (b · c)              [definition] by folding multiplication at suc a

Here ·-assoc a b c is the induction hypothesis for the smaller first factor a;
·-distribʳ-+ is instead the distributivity theorem already proved above.
-}

·-assoc : (a b c : ℕ) → (a · b) · c ≡ a · (b · c)
·-assoc zero b c = refl
·-assoc (suc a) b c = (·-distribʳ-+ b (a · b) c) ∙ (cong (λ x → (b · c) + x) (·-assoc a b c) )

{-
Supporting lemma for Theorem 8: Successor in the right factor

Statement
---------
For all natural numbers n and m,
  n · suc m ≡ n + (n · m).

Relevant definitions
--------------------
Multiplication recurses on its first argument:
  zero  · m = zero
  suc n · m = m + (n · m)

Previous results and tools
--------------------------
  +-assoc  : associativity of addition
  +-comm   : commutativity of addition
  +-sucʳ   : n + suc m ≡ suc (n + m)

The suc case uses the induction hypothesis ·-sucʳ n m and then rearranges
the resulting sum into the shape required by the right-hand side.

Path calculation
----------------
zero case:
  zero · suc m
    ≡ zero                         [definition] by reducing zero · suc m
    ≡ zero + zero · m              [definition] by folding zero · m and zero + zero

suc case:
  suc n · suc m
    ≡ suc m + (n · suc m)          [definition] by unfolding multiplication at suc n
    ≡ suc m + (n + n · m)          [induction hypothesis] by cong (suc m +_) applied to ·-sucʳ n m
    ≡ (suc m + n) + n · m          [previous theorem] by sym (+-assoc (suc m) n (n · m)), using Theorem 3
    ≡ (n + suc m) + n · m          [previous theorem] by cong (_+ n · m) applied to +-comm (suc m) n, using Theorem 4
    ≡ suc (n + m) + n · m          [previous lemma] by cong (_+ n · m) applied to +-sucʳ n m
    ≡ (suc n + m) + n · m          [definition] since suc n + m reduces to suc (n + m)
    ≡ suc n + (m + n · m)          [previous theorem] by +-assoc (suc n) m (n · m), using Theorem 3
    ≡ suc n + (suc n · m)          [definition] by folding suc n · m

Only the second displayed step uses the induction hypothesis ·-sucʳ n m.
All later non-definitional steps use addition results proved earlier.
-}

·-sucʳ : (n m : ℕ) → n · suc m ≡ n + (n · m)
·-sucʳ zero m = refl
·-sucʳ (suc n) m = 
   (cong (λ x → suc m + x) (·-sucʳ n m)) 
   ∙ (sym (+-assoc (suc m) n (n · m)) )
   ∙ (cong (λ x → x + (n · m)) (+-comm (suc m) n) )
   ∙ (cong (λ x → x + (n · m)) (+-sucʳ n m) )
   ∙ (+-assoc (suc n) m (n · m))




{-
Theorem 8: Commutativity of multiplication

Statement
---------
For all natural numbers a and b,
  a · b ≡ b · a.

Relevant definitions
--------------------
Multiplication recurses on its first argument:
  zero  · b = zero
  suc a · b = b + (a · b)

Previous results and tools
--------------------------
  ·-zeroʳ b : b · zero ≡ zero
  ·-sucʳ b a : b · suc a ≡ b + b · a

The suc case uses the induction hypothesis ·-comm a b under the outer
function `b +_`.

Path calculation
----------------
zero case:
  zero · b
    ≡ zero                         [definition] by reducing zero · b
    ≡ b · zero                     [previous theorem] by sym (·-zeroʳ b), using Theorem 5

suc case:
  suc a · b
    ≡ b + a · b                    [definition] by unfolding multiplication at suc a
    ≡ b + b · a                    [induction hypothesis] by cong (b +_) applied to ·-comm a b
    ≡ b · suc a                    [previous lemma] by sym (·-sucʳ b a)

The occurrence ·-comm a b is the induction hypothesis for the smaller first
factor a. The final step uses the supporting lemma ·-sucʳ proved above.
-}

·-comm : (a b : ℕ) → a · b ≡ b · a
·-comm zero b = sym (·-zeroʳ b)
·-comm (suc a) b =  (cong (λ x → b + x) (·-comm a b)) ∙ (sym (·-sucʳ b a))


{-
Theorem 9: One is a two-sided identity for multiplication

Statement
---------
For every natural number a,
  1 · a ≡ a                    (left identity)
and
  a · 1 ≡ a                    (right identity).

Relevant definitions
--------------------
The numeral 1 is suc zero. Multiplication recurses on its first argument:
  zero  · a = zero
  suc n · a = a + (n · a)

Consequently,
  1 · a
    = suc zero · a
    = a + (zero · a)
    = a + zero.

Previous results and tools
--------------------------
  +-zeroʳ a : a + zero ≡ a
  ·-comm a 1 : a · 1 ≡ 1 · a

The right-identity proof also uses the left-identity result 1-is-unitˡ a.

Path calculation
----------------
Left identity (no induction is needed):
  1 · a
    ≡ a + zero                     [definition] by unfolding 1 = suc zero and then _·_
    ≡ a                            [previous theorem] by +-zeroʳ a, using Theorem 1

Right identity (no induction is needed):
  a · 1
    ≡ 1 · a                        [previous theorem] by ·-comm a 1, using Theorem 8
    ≡ a                            [previous result] by the left-identity proof 1-is-unitˡ a

The two Agda clauses below follow these two paths exactly.
-}

1-is-unitˡ : (a : ℕ) → 1 · a ≡ a
1-is-unitˡ a = +-zeroʳ a  


1-is-unitʳ : (a : ℕ) → a · 1 ≡ a
1-is-unitʳ a = (·-comm a 1) ∙ (1-is-unitˡ a)
